def minuscule(chaine):
    copie = ...
    for caractere in chaine:
        code = ...
        if ...("A") <= ... <= ...:
            code = ...
        copie = ...
    return ...

# Tests

assert minuscule("ABCDE") == "abcde"
chaine = "Les algorithmes de Bellman-Ford et de Dijkstra."
assert minuscule(chaine) == "les algorithmes de bellman-ford et de dijkstra."
